humhub/app@master:
  - source: assets/
    deleteOrphaned: true
    exclude: |
      .env
  - source: lib/
    deleteOrphaned: true
  - source: test/
    deleteOrphaned: true
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml
humhub/app-flavored@master:
  - source: assets/
    deleteOrphaned: true
    exclude: |
      .env
  - source: lib/
    deleteOrphaned: true
  - source: test/
    deleteOrphaned: true
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml
humhub/app-inforisque-leclub@master:
  - source: assets/
    deleteOrphaned: true
    exclude: |
      .env
  - source: lib/
    deleteOrphaned: true
  - source: test/
    deleteOrphaned: true
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml