humhub/app@f-flavored:
  - assets/
  - lib/
  - test/
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml
humhub/app-flavored@main:
  - assets/
  - lib/
  - test/
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml