name: Increment Build Number

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set build number
        run: |
          if [ -z "$BUILD_NUMBER" ]; then
            echo "Build number is not set, initializing to just run"
            export BUILD_NUMBER=42
          else
            echo "Build number is $BUILD_NUMBER, incrementing by 1"
            export BUILD_NUMBER=$((BUILD_NUMBER+1))
          fi
          echo "New build number is $BUILD_NUMBER"
      - name: Use build number
        run: echo "Build number is $BUILD_NUMBER"
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}