name: flutter-test
on: push
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
      - uses: subosito/flutter-action@v1
      - name: Lint
      - run: flutter analyze
      - name: Test
      - run: flutter test --coverage
       if: success()