name: flutter-test
on:
  push:
    branches: [f-milestone-v0.1]
jobs:
  build_apk:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Build APK
        run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk-${{ github.run_number }}
          path: build/app/outputs/apk/release/app-release.apk